name: my_flutter_wechat
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^0.5.0+1
  toast: ^0.1.3
  image_picker: ^0.5.0+9
  pull_to_refresh_notification: ^0.2.0
  url_launcher: ^5.0.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/tabbar_contacts.png
    - images/tabbar_contacts_hl.png
    - images/tabbar_discover.png
    - images/tabbar_discover_hl.png
    - images/tabbar_mainframe.png
    - images/tabbar_mainframe_hl.png
    - images/tabbar_me.png
    - images/tabbar_me_hl.png

    - images/defaultHead.png
    - images/nav_icon_back.png
    - images/nav_icon_back_white.png
    - images/nav_icon_more.png

    - images/nav_icon_menu_addfriend.png
    - images/nav_icon_menu_chat.png
    - images/nav_icon_menu_pay.png
    - images/nav_icon_menu_scan.png

    - images/userinfo_icon_videoCall.png
    - images/userinfo_icon_chats.png
    - images/voip_actionSheet_voice.png
    - images/voip_actionSheet_video.png


    - images/add_friend_icon_FriendNotify.png
    - images/add_friend_icon_addgroup.png
    - images/add_friend_icon_ContactTag.png
    - images/add_friend_icon_offical.png

    - images/moment_icon_moment.png
    - images/moment_icon_scan.png
    - images/moment_icon_shake.png
    - images/moment_icon_news.png
    - images/moment_icon_search.png
    - images/moment_icon_nearby.png
    - images/moment_icon_wxapp.png
    - images/moment_icon_op.png
    - images/moment_icon_comment_white.png
    - images/moment_icon_like_white.png

    - images/moment_icon_at.png
    - images/moment_icon_me.png
    - images/moment_icon_location.png
    - images/moment_icon_QQSpaceBig.png
    - images/moment_icon_QQSpaceBigHL.png
    - images/moment_icon_album_add.png


    - images/chat_icon_toolbar_addmore.png
    - images/chat_icon_toolbar_keyboard.png
    - images/chat_icon_toolbar_sticker.png
    - images/chat_icon_toolbar_voice.png
    - images/chat_detail_addGroupMember.png

    - images/tableview_arrow.png
    - images/mine_icon_homeQR.png

    - images/mine_icon_wechatpay.png
    - images/mine_icon_favorites.png
    - images/mine_icon_album.png
    - images/mine_icon_cards.png
    - images/mine_icon_sticker.png
    - images/mine_icon_setting.png

    - images/nav_icon_mine_camera.png
    - images/nav_icon_contact_addfriend.png
    - images/nav_icon_moment_black_camera.png
    - images/nav_icon_moment_white_camera.png

    - content/chatInfo.json
    - images/moment_header_bg.jpg
    - images/searchBar_icon.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
